FROM ubuntu:14.04

RUN apt-get update && apt-get install -y software-properties-common
RUN apt-add-repository ppa:brightbox/ruby-ng
RUN apt-get update -y && apt-get install -y ruby2.2 dpkg-dev

ADD ci/install.sh /

CMD [ "/install.sh" ]
