FROM @@image@@

RUN mkdir -p /src/opt/conjur/project

WORKDIR /src/opt/conjur/project

COPY Gemfile ./
COPY Gemfile.lock ./
COPY *.gemspec ./
COPY lib/conjur/version.rb ./lib/conjur/

RUN bundle
# debify wants to see this
RUN mkdir -p vendor/bundle

COPY . .

RUN bundle binstubs conjur-cli --path=/usr/local/bin

ADD debify.sh /

WORKDIR /src
